import { MessageDescriptor } from "@lingui/core"
import { msg } from "@lingui/core/macro"

type ControlKeyLabels = Record<string, string | MessageDescriptor>

export const keyboardKeyLabels: ControlKeyLabels = {
  ArrowLeft: msg`Left Arrow`,
  ArrowRight: msg`Right Arrow`,
  ArrowUp: msg`Up Arrow`,
  ArrowDown: msg`Down Arrow`,
  Space: msg`Space`,
  Delete: msg`Delete`,
  Insert: msg`Insert`,
  Home: msg`Home`,
  End: msg`End`,
  PageUp: msg`Page Up`,
  PageDown: msg`Page Down`,

  // Number keys
  Digit0: "0",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",

  // Letter keys
  KeyA: "A",
  KeyB: "B",
  KeyC: "C",
  KeyD: "D",
  KeyE: "E",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyI: "I",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  KeyM: "M",
  KeyN: "N",
  KeyO: "O",
  KeyP: "P",
  KeyQ: "Q",
  KeyR: "R",
  KeyS: "S",
  KeyT: "T",
  KeyU: "U",
  KeyV: "V",
  KeyW: "W",
  KeyX: "X",
  KeyY: "Y",
  KeyZ: "Z",

  // Numpad
  Numpad0: msg`Numpad 0`,
  Numpad1: msg`Numpad 1`,
  Numpad2: msg`Numpad 2`,
  Numpad3: msg`Numpad 3`,
  Numpad4: msg`Numpad 4`,
  Numpad5: msg`Numpad 5`,
  Numpad6: msg`Numpad 6`,
  Numpad7: msg`Numpad 7`,
  Numpad8: msg`Numpad 8`,
  Numpad9: msg`Numpad 9`,
  NumpadEqual: msg`Numpad =`,
  NumpadDivide: msg`Numpad /`,
  NumpadMultiply: msg`Numpad *`,
  NumpadSubtract: msg`Numpad -`,
  NumpadAdd: msg`Numpad +`,
  NumpadDecimal: msg`Numpad .`,

  // Symbols
  Minus: "-",
  Equal: "=",
  BracketLeft: "[",
  BracketRight: "]",
  Slash: "/",
  Backslash: "\\",
  Semicolon: ";",
  Quote: "'",
  Backquote: "`",
  Comma: ",",
  Period: ".",
}
